import { Band } from '../types';
import { SERVICES_COMBINATIONS } from './servicesCombinations';
import { SOLOISTS } from './soloists';

export const BANDS: Band[] = [
    {
        name: 'Pianista',
        ceremonyPrice: 500,
        cocktailPrice: 700,
        feastPrice: 850,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ALL,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Cantante & Guitarra',
        ceremonyPrice: 350,
        cocktailPrice: 450,
        feastPrice: 550,
        partyPrice: undefined,
        serviceCombinations:
            SERVICES_COMBINATIONS.CEREMONY_AND_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,

        // Exclude Laura Soprano from the list of soloists
        availableSoloists: SOLOISTS.SINGERS.filter(
            (soloist) =>
                soloist.name !== 'Laura Soprano' &&
                soloist.name !== 'Elvira Soul' &&
                soloist.name !== 'Sofia Bossa'
        ),
    },
    {
        name: 'Cantante & Piano',
        ceremonyPrice: 350,
        cocktailPrice: 450,
        feastPrice: 550,
        partyPrice: undefined,
        serviceCombinations:
            SERVICES_COMBINATIONS.CEREMONY_AND_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.SINGERS,
    },
    {
        name: 'Cantante, Guitarra & Piano',
        ceremonyPrice: 700,
        cocktailPrice: 850,
        feastPrice: 950,
        partyPrice: undefined,
        serviceCombinations:
            SERVICES_COMBINATIONS.CEREMONY_AND_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.SINGERS.filter(
            (soloist) => soloist.name !== 'Laura Soprano'
        ),
    },
    {
        name: 'Latin Quartet',
        ceremonyPrice: undefined,
        cocktailPrice: 1750,
        feastPrice: 2100,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ONLY_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: '2Cellos',
        ceremonyPrice: 700,
        cocktailPrice: 950,
        feastPrice: 1150,
        partyPrice: undefined,
        serviceCombinations:
            SERVICES_COMBINATIONS.CEREMONY_AND_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Jazz Quartet',
        ceremonyPrice: undefined,
        cocktailPrice: 1750,
        feastPrice: 2100,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.ELVIRA_AND_CARMEN,
    },
    {
        name: 'Jazz Trio',
        ceremonyPrice: undefined,
        cocktailPrice: 1500,
        feastPrice: 1800,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.ELVIRA_AND_CARMEN,
    },
    {
        name: 'Soul Quintet',
        ceremonyPrice: undefined,
        cocktailPrice: 2200,
        feastPrice: 2600,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Camerata',
        ceremonyPrice: 3600,
        cocktailPrice: undefined,
        feastPrice: undefined,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ONLY_CEREMONIES,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Concuerda & Co (Duo)',
        ceremonyPrice: 700,
        cocktailPrice: 950,
        feastPrice: 1250,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ALL_EXCLUDING_PARTY,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.ALL,
    },
    {
        name: 'Concuerda & Co (Trio)',
        ceremonyPrice: 850,
        cocktailPrice: 1150,
        feastPrice: 1400,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ALL_EXCLUDING_PARTY,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.ALL,
    },
    {
        name: 'Concuerda & Co (Quartet)',
        ceremonyPrice: 1000,
        cocktailPrice: 1300,
        feastPrice: 1650,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ALL_EXCLUDING_PARTY,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.ALL,
    },
    {
        name: 'Trio Concuerda',
        ceremonyPrice: 1500,
        cocktailPrice: 2200,
        feastPrice: 2600,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ALL_EXCLUDING_PARTY,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Gipsy Jazz',
        ceremonyPrice: undefined,
        cocktailPrice: 1650,
        feastPrice: 2000,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.DAN_AND_ELVIRA_AND_CARMEN,
    },
    {
        name: 'Gipsy Jazz (Trio)',
        ceremonyPrice: undefined,
        cocktailPrice: 2100,
        feastPrice: 2450,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.DAN_AND_ELVIRA_AND_CARMEN,
    },
    {
        name: 'Gipsy Jazz (Quartet)',
        ceremonyPrice: undefined,
        cocktailPrice: 2750,
        feastPrice: 3100,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.DAN_AND_ELVIRA_AND_CARMEN,
    },
    {
        name: 'Crooner Band',
        ceremonyPrice: undefined,
        cocktailPrice: 2150,
        feastPrice: 2550,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'String Band',
        ceremonyPrice: undefined,
        cocktailPrice: 3000,
        feastPrice: 3500,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.ALL.filter(
            (soloist) =>
                !['Laura', 'Carmen', 'Sofia', 'Fred', 'Inoidel'].includes(
                    soloist.name
                )
        ),
    },
    {
        name: 'Pop Band',
        ceremonyPrice: undefined,
        cocktailPrice: 1450,
        feastPrice: 1750,
        partyPrice: 2000,
        serviceCombinations: SERVICES_COMBINATIONS.PARTY_AND_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Rock Band (con Luis Rock)',
        ceremonyPrice: undefined,
        cocktailPrice: 2200,
        feastPrice: 2600,
        partyPrice: 3000,
        serviceCombinations: SERVICES_COMBINATIONS.PARTY_AND_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Funky Band',
        ceremonyPrice: undefined,
        cocktailPrice: 2000,
        feastPrice: 2400,
        partyPrice: 2800,
        serviceCombinations: SERVICES_COMBINATIONS.PARTY_AND_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.ALL.filter(
            (soloist) => !['Laura', 'Carmen', 'Sofia'].includes(soloist.name)
        ),
    },
    {
        name: 'Duo Flamenco',
        ceremonyPrice: undefined,
        cocktailPrice: 1250,
        feastPrice: 1650,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ONLY_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Duo Rumbero',
        ceremonyPrice: undefined,
        cocktailPrice: 1250,
        feastPrice: 1650,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ONLY_COCKTAIL_OR_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Coro Gospel',
        ceremonyPrice: 2450,
        cocktailPrice: 3200,
        feastPrice: undefined,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.CEREMONY_AND_COCKTAIL,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Coro Gospel con Piano',
        ceremonyPrice: 2750,
        cocktailPrice: 3500,
        feastPrice: undefined,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.CEREMONY_AND_COCKTAIL,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Coro Gospel con Concuerda & Co',
        ceremonyPrice: 3200,
        cocktailPrice: 4150,
        feastPrice: undefined,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.CEREMONY_AND_COCKTAIL,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Coro Gospel con Trio Concuerda',
        ceremonyPrice: 3800,
        cocktailPrice: 5250,
        feastPrice: undefined,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.CEREMONY_AND_COCKTAIL,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.NONE,
    },
    {
        name: 'Saxo',
        ceremonyPrice: undefined,
        cocktailPrice: 900,
        feastPrice: 1050,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: false,
        availableSoloists: SOLOISTS.SINGERS,
    },
    {
        name: 'Saxo & Piano',
        ceremonyPrice: 850,
        cocktailPrice: 1150,
        feastPrice: 1450,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.ALL_EXCLUDING_PARTY,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.SINGERS,
    },
    {
        name: 'Bossanova Quartet',
        ceremonyPrice: undefined,
        cocktailPrice: 2150,
        feastPrice: 2550,
        partyPrice: undefined,
        serviceCombinations: SERVICES_COMBINATIONS.COCKTAIL_AND_FEAST,
        canHaveCandles: true,
        canHaveGrandPiano: true,
        availableSoloists: SOLOISTS.NONE,
    },
];

// Higher the price of the soloists a 10%
export const BANDS_WITH_10_PERCENT_MORE = BANDS.map((band) => ({
    ...band,
    ceremonyPrice: band.ceremonyPrice ? band.ceremonyPrice * 1.1 : undefined,
    cocktailPrice: band.cocktailPrice ? band.cocktailPrice * 1.1 : undefined,
    feastPrice: band.feastPrice ? band.feastPrice * 1.1 : undefined,
    partyPrice: band.partyPrice ? band.partyPrice * 1.1 : undefined,
}));
